# render.yaml - CORRECTED BLUEPRINT

services:
  # ----------------- #
  #  Postiz Web App   #
  # ----------------- #
  - type: web
    name: postiz
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postiz-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: pserv
          name: postiz-redis
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: MAIN_URL
        value: ""
      - key: FRONTEND_URL
        value: ""
      - key: NEXT_PUBLIC_BACKEND_URL
        value: ""

  # ----------------- #
  #    Redis Cache    #
  # ----------------- #
  - type: redis
    name: postiz-redis
    ipAllowList: []
    plan: free

# Correctly outdented to the root level
databases:
  # ----------------- #
  #   PostgreSQL DB   #
  # ----------------- #
  - name: postiz-db
    databaseName: postiz
    user: postiz
    plan: free
