# render.yaml - Final Blueprint Configuration

services:
  # 1. The Postiz Web Application Service
  - type: web
    name: postiz
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postiz-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis # ← fixed this from pserv to redis
          name: postiz-redis
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: MAIN_URL
        value: ""
      - key: FRONTEND_URL
        value: ""
      - key: NEXT_PUBLIC_BACKEND_URL
        value: ""

  # 2. The Redis Cache Service
  - type: redis
    name: postiz-redis
    plan: free
    ipAllowList: []

databases:
  # 3. The PostgreSQL Database
  - name: postiz-db
    databaseName: postiz
    user: postiz
    plan: free
