# render.yaml - CORRECTED BLUEPRINT

# The top-level 'services' key holds all running applications and services.
services:
  # ----------------- #
  #  Postiz Web App   #
  # ----------------- #
  - type: web
    name: postiz
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postiz-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: pserv # Note: When linking to Redis, you still use 'pserv'
          name: postiz-redis
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: MAIN_URL
        value: "" # You will set this in the Render UI after the first deploy
      - key: FRONTEND_URL
        value: "" # You will set this in the Render UI after the first deploy
      - key: NEXT_PUBLIC_BACKEND_URL
        value: "" # You will set this in the Render UI after the first deploy

  # ----------------- #
  #    Redis Cache    #
  # ----------------- #
  # Redis is defined as a service, not a database.
  - type: redis # <<< THIS IS THE KEY CHANGE
    name: postiz-redis
    ipAllowList: []
    plan: free

# The top-level 'databases' key is only for PostgreSQL.
databases:
  # ----------------- #
  #   PostgreSQL DB   #
  # ----------------- #
  - name: postiz-db
    databaseName: postiz
    user: postiz
    plan: free
